version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_MULTIPLE_DBS: alunosdb,cursosdb,inscricoesdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    networks:
      - plataforma-net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d cursosdb" ]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    build: ./nginx
    restart: always
    container_name: nginx_gateway
    ports:
      - "8080:80"
    networks:
      - plataforma-net
    depends_on:
      servico-cursos-1:
        condition: service_started
      servico-cursos-2:
        condition: service_started
      servico-alunos:
        condition: service_started
      servico-inscricoes:
        condition: service_started

  servico-cursos-1:
    build: ./servico-cursos
    container_name: servico-cursos-1
    environment:
      - PORT=8081
    ports:
      - "8081:8081"
    networks:
      - plataforma-net
    depends_on:
      postgres:
        condition: service_healthy

  servico-cursos-2:
    build: ./servico-cursos
    container_name: servico-cursos-2
    environment:
      - PORT=8081
    ports:
      - "8084:8081"
    networks:
      - plataforma-net
    depends_on:
      postgres:
        condition: service_healthy

  servico-alunos:
    build: ./servico-alunos
    container_name: servico-alunos
    ports:
      - "8082:8082"
    environment:
      - PORT=8082
    networks:
      - plataforma-net
    depends_on:
      postgres:
        condition: service_healthy

  servico-inscricoes:
    build: ./servico-inscricoes
    container_name: servico-inscricoes
    ports:
      - "8083:8083"
    environment:
      - PORT=8083
    networks:
      - plataforma-net
    depends_on:
      servico-alunos:
        condition: service_started
      servico-cursos-1:
          condition: service_started
      servico-cursos-2:
        condition: service_started
      postgres:
        condition: service_healthy

networks:
  plataforma-net:
    driver: bridge

volumes:
  postgres_data:

