version: '3.8'

services:

  nginx:
    build: ./nginx
    container_name: nginx_gateway
    ports:
      - "8080:80"
    networks:
      - plataforma-net
    depends_on:
      - servico-cursos-1
      - servico-cursos-2
      - servico-alunos
      - servico-inscricoes

  servico-cursos-1:
    build: ./Servico-Cursos
    container_name: servico-cursos-1
    environment:
      - PORT=8081
    networks:
      - plataforma-net

  servico-cursos-2:
    build: ./Servico-Cursos
    container_name: servico-cursos-2
    environment:
      - PORT=8081
    networks:
      - plataforma-net

  servico-alunos:
    build: ./Servico-Alunos
    container_name: servico-alunos
    environment:
      - PORT=8082
    networks:
      - plataforma-net

  servico-inscricoes:
    build: ./Servico-Inscricoes
    container_name: servico-inscricoes
    environment:
      - PORT=8083
    networks:
      - plataforma-net

networks:
  plataforma-net:
    driver: bridge